# Generated by Django 5.0.6 on 2024-06-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=12)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion_empresa', models.CharField(max_length=150)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('correo_electronico', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plantillas.rol')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
