# Generated by Django 5.0.6 on 2024-06-10 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_cancha',
            fields=[
                ('id_tipo_cancha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='img/categorias/')),
                ('descripcion', models.TextField()),
                ('cantidad_cancha', models.IntegerField()),
                ('categoria_tipo_cancha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=210, null=True)),
                ('subdescripcion', models.CharField(blank=True, max_length=210, null=True)),
                ('capacidad', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.tipo_cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recomendacion', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('horaapertura', models.TimeField()),
                ('horacierre', models.TimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.cancha')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/canchas/')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='administrador.cancha')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id_rede_social', models.AutoField(primary_key=True, serialize=False)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.cancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='administrador.cancha')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.region'),
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('estado', models.BooleanField(default=False)),
                ('cancha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.cancha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
