# Generated by Django 5.0.6 on 2024-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
