# Generated by Django 5.0.6 on 2024-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_remove_cancha_favorito_favorito_delete_redesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='esrado',
            field=models.BooleanField(default=False),
        ),
    ]
