# Generated by Django 5.0.6 on 2024-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_cancha_created_at_alter_cancha_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
