# Generated by Django 5.0.6 on 2024-07-01 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTransferencia',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('vista', 'Cuenta Vista'), ('cuenta_rut', 'Cuenta RUT'), ('ahorro_vivienda', 'Cuenta de Ahorro para la Vivienda')], max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.banco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
