# Generated by Django 5.0.6 on 2024-07-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_datostransferencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datostransferencia',
            old_name='id_transferencia',
            new_name='id_datos_transferencia',
        ),
    ]
