# Generated by Django 5.0.6 on 2024-07-02 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_rename_id_transferencia_datostransferencia_id_datos_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pago', models.CharField(default='No transferido', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.reserva')),
                ('usuario_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
