# Generated by Django 5.0.6 on 2024-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='total_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
