# Generated by Django 5.0.6 on 2024-07-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_pagos_total_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='foto_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='img/comprobantes/'),
        ),
    ]
